In [2]:
import numpy as np
import pandas as pd
import math

In [8]:
# Part-I: Sigmoid Function
# 1. Function using math.exp()
def mysigmoid(x):
    return 1 / (1 + math.exp(-x))

In [10]:
# 2. Call mysigmoid() with x=4
sigmoid_4 = mysigmoid(4)
print("Sigmoid value of 4:", sigmoid_4)

Sigmoid value of 4: 0.9820137900379085


In [11]:
# 3. Sigmoid values for x=[1, 2, 3]
x = [1, 2, 3]
sigmoid_x = [mysigmoid(val) for val in x]
print("Sigmoid values for x=[1, 2, 3]:", sigmoid_x)

Sigmoid values for x=[1, 2, 3]: [0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


In [12]:
# 4. Function using np.exp()
def mysigmoid_np(x):
    x = np.array(x)  # Convert x to a NumPy array
    return 1 / (1 + np.exp(-x))

In [13]:
# 5. Call the function with x=[1, 2, 3]
sigmoid_x_np = mysigmoid_np(x)
print("Sigmoid values for x=[1, 2, 3] (using np.exp()):", sigmoid_x_np)

Sigmoid values for x=[1, 2, 3] (using np.exp()): [0.73105858 0.88079708 0.95257413]


In [14]:
# 6. Scalar vs. Vector
scalar = 2
vector = np.array([1, 2, 3])

In [15]:
print("Scalar multiplied by 2:", scalar * 2)
print("Vector multiplied by 2:", vector * 2)

Scalar multiplied by 2: 4
Vector multiplied by 2: [2 4 6]


In [16]:
# Part-II: Gradient of Sigmoid Function

In [17]:
# Function to compute sigmoid derivative
def sig_derivative(s):
    sigmoid_value = mysigmoid(s)
    return sigmoid_value * (1 - sigmoid_value)

In [18]:
# Call the function with a sigmoid value
s = 0.7
sigmoid_derivative = sig_derivative(s)
print("Sigmoid derivative for s=0.7:", sigmoid_derivative)

Sigmoid derivative for s=0.7: 0.22171287329310904


In [19]:
# Part-II: Gradient or derivative of sigmoid function

In [20]:
def sig_derivative(s):
    sigmoid_value = mysigmoid(s)
    return sigmoid_value * (1 - sigmoid_value)


In [21]:
# Part-III: image_to_vector()


In [22]:
def image_to_vector(image):
    length, height, depth = image.shape
    vector = image.reshape((length * height * depth, 1))
    return vector

In [23]:
# Test with a 3x3x2 array of RGB color values
image = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                  [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                  [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
vector = image_to_vector(image)
print("Image shape:", image.shape)
print("Vector shape:", vector.shape)
print("Vector:")
print(vector)

Image shape: (3, 3, 3)
Vector shape: (27, 1)
Vector:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]]


In [24]:
# Part-IV: normalizeRows()


In [25]:
def normalizeRows(matrix):
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    return matrix / norms


In [26]:
# Test with a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
normalized_matrix = normalizeRows(matrix)
print("Original matrix:")
print(matrix)
print("Normalized matrix:")
print(normalized_matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized matrix:
[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]


In [27]:
# Part-V: Multiplication and Vectorization Operations

In [28]:
# a) Multiplication and dot product of two vectors
x1 = np.array([9, 2, 5])
x2 = np.array([7, 2, 2])

multiplication_result = np.multiply(x1, x2)
dot_product_result = np.dot(x1, x2)

print("Multiplication result (manual):", multiplication_result)
print("Dot product result (manual):", dot_product_result)


Multiplication result (manual): [63  4 10]
Dot product result (manual): 77


In [29]:
# b) Multiplication and dot product of two longer vectors
x1 = np.array([9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0, 4, 5, 7])
x2 = np.array([7, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0, 8, 5, 3])

multiplication_result = np.multiply(x1, x2)
dot_product_result = np.dot(x1, x2)

print("Multiplication result (manual):", multiplication_result)
print("Dot product result (manual):", dot_product_result)

Multiplication result (manual): [63  4 10  0  0 63 10  0  0  0 81  4 25  0  0 32 25 21]
Dot product result (manual): 338


In [30]:
# Part-VI: L1 and L2 loss functions

In [31]:
def loss_l1(y, ypred):
    return np.sum(np.abs(y - ypred))

In [32]:
def loss_l2(y, ypred):
    return np.sum(np.square(y - ypred))

In [33]:
# Test with sample vectors
y = np.array([1, 0, 0, 1, 1])
ypred = np.array([0.9, 0.2, 0.1, 0.4, 0.9])

In [34]:
l1_loss = loss_l1(y, ypred)
l2_loss = loss_l2(y, ypred)

In [35]:
print("L1 loss:", l1_loss)
print("L2 loss:", l2_loss)

L1 loss: 1.1
L2 loss: 0.43
